/*
Deployment script for Portfolio

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
USE Portfolio
--REPLACE WITH YOUR LOCAL DB NAME -- AND ALSO TOWARD THE END 

GO
PRINT N'Creating [dbo].[Portfolio]...';


GO
CREATE TABLE [dbo].[Portfolio] (
    [StockId]  INT NOT NULL,
    [UserId]   INT NOT NULL,
    [Quantity] INT NULL,
    CONSTRAINT [PK_Portfolio] PRIMARY KEY CLUSTERED ([StockId] ASC, [UserId] ASC)
);


GO
PRINT N'Creating [dbo].[Stock]...';


GO
CREATE TABLE [dbo].[Stock] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [Symbol]      NVARCHAR (10)  NULL,
    [LastPrice]   FLOAT (53)     NULL,
    [CompanyName] NVARCHAR (100) NULL,
    CONSTRAINT [PK_Stock] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[StockHistory]...';


GO
CREATE TABLE [dbo].[StockHistory] (
    [Id]              INT        IDENTITY (1, 1) NOT NULL,
    [StockId]         INT        NOT NULL,
    [ObservationTime] DATETIME   NULL,
    [Price]           FLOAT (53) NULL,
    [IsEod]           BIT        NOT NULL,
    CONSTRAINT [PK_StockHisotry] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[TransactionLog]...';


GO
CREATE TABLE [dbo].[TransactionLog] (
    [Id]              INT        IDENTITY (1, 1) NOT NULL,
    [StockId]         INT        NULL,
    [Quantity]        INT        NULL,
    [Price]           FLOAT (53) NULL,
    [Purchased]       BIT        NULL,
    [TransactionDate] DATETIME   NULL,
    CONSTRAINT [PK_TransactionLog] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Users]...';


GO
CREATE TABLE [dbo].[Users] (
    [ID]        INT            IDENTITY (1, 1) NOT NULL,
    [Name]      NVARCHAR (100) NULL,
    [CashValue] FLOAT (53)     NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating unnamed constraint on [dbo].[StockHistory]...';


GO
ALTER TABLE [dbo].[StockHistory]
    ADD DEFAULT ((0)) FOR [IsEod];


GO
PRINT N'Creating [dbo].[FK_Portfolio_Stock]...';


GO
ALTER TABLE [dbo].[Portfolio] WITH NOCHECK
    ADD CONSTRAINT [FK_Portfolio_Stock] FOREIGN KEY ([StockId]) REFERENCES [dbo].[Stock] ([ID]);


GO
PRINT N'Creating [dbo].[FK_Portfolio_User]...';


GO
ALTER TABLE [dbo].[Portfolio] WITH NOCHECK
    ADD CONSTRAINT [FK_Portfolio_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users] ([ID]);


GO
PRINT N'Creating [dbo].[FK_StockHistory_Stock]...';


GO
ALTER TABLE [dbo].[StockHistory] WITH NOCHECK
    ADD CONSTRAINT [FK_StockHistory_Stock] FOREIGN KEY ([StockId]) REFERENCES [dbo].[Stock] ([ID]);


GO
PRINT N'Creating [dbo].[FK_TransactionLog_Stock]...';


GO
ALTER TABLE [dbo].[TransactionLog] WITH NOCHECK
    ADD CONSTRAINT [FK_TransactionLog_Stock] FOREIGN KEY ([StockId]) REFERENCES [dbo].[Stock] ([ID]);


GO
PRINT N'Creating [dbo].[v_CurrentPrices]...';


GO



CREATE VIEW dbo.v_CurrentPrices
AS
SELECT 
	s.ID AS StockId,
	s.Symbol AS Symbol,
	s.CompanyName AS CompanyName,
	h.Price AS CurrentPrice
FROM (SELECT 
	s.ID AS StockId,
	MAX(h.ObservationTime) AS MaxObservationTime
FROM Stock s
JOIN STockHistory h on h.StockId = s.ID
GROUP BY s.ID) m
JOIN Stock s on s.ID = m.StockId
JOIN StockHistory h on h.StockId = s.ID AND h.ObservationTime = m.MaxObservationTime
GO
PRINT N'Checking existing data against newly created constraints';


GO
USE Portfolio


GO
ALTER TABLE [dbo].[Portfolio] WITH CHECK CHECK CONSTRAINT [FK_Portfolio_Stock];

ALTER TABLE [dbo].[Portfolio] WITH CHECK CHECK CONSTRAINT [FK_Portfolio_User];

ALTER TABLE [dbo].[StockHistory] WITH CHECK CHECK CONSTRAINT [FK_StockHistory_Stock];

ALTER TABLE [dbo].[TransactionLog] WITH CHECK CHECK CONSTRAINT [FK_TransactionLog_Stock];


GO
PRINT N'Update complete.';


GO
