//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Manager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CurrentPrices
    {
        public int StockId { get; set; }
        public string Symbol { get; set; }
        public string CompanyName { get; set; }
        public Nullable<double> CurrentPrice { get; set; }
    }
}
